version: "3.9"

services:
  mongodb:
    image: mongo:8
    container_name: dorahotel-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dorahotel
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: